### ISSUE TITLE
audio send function

### ISSUE THREAD

**Issue by matheusccarvalho** [eltorodev/instagram-direct-page#1]
Hello Friend. Does this project have the function of sending audio? I'm building a chrome extension to add the function of sending audios and loading audios

**Comment by eltorodev** [comment]
Hi, this is just a theme made with Bootstrap 4.x. but i can add the audio icon latter...

**Comment by matheusccarvalho** [comment]
Guilherme, have you seen any tools that can send audios through instagram desktop? In this case, upload an audio and send it in the chat.

**Comment by eltorodev** [comment]
I can not help 😥

**Comment by guilhermealves18** [comment]
> Olá amigo. Esse projeto tem a função de enviar áudio? Estou construindo uma extensão do chrome para adicionar a função de enviar áudios e carregar áudios

You did it?
